name: raptor
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  go_router: ^14.2.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  fpdart: ^1.1.0
  get_it: ^8.0.2
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#182A3A"
  image: "assets/images/splash_icon.png"
  android: true
  ios: true