// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGLX3V4DZfMcN1x2K_cggro8w7hk8ExY',
    appId: '1:454808577764:web:914240b49ae56103722ef1',
    messagingSenderId: '454808577764',
    projectId: 'raptor-12312',
    authDomain: 'raptor-12312.firebaseapp.com',
    storageBucket: 'raptor-12312.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTumBXEeT-25ceO0jltuk8s7OMbqKdF0',
    appId: '1:454808577764:android:d1127b18d7d5e44e722ef1',
    messagingSenderId: '454808577764',
    projectId: 'raptor-12312',
    storageBucket: 'raptor-12312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLiehxRG-0UImE5zNb1Jx7uPfrZxZPKBg',
    appId: '1:454808577764:ios:598ed751636eef18722ef1',
    messagingSenderId: '454808577764',
    projectId: 'raptor-12312',
    storageBucket: 'raptor-12312.appspot.com',
    iosBundleId: 'com.example.raptor',
  );
}
